import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	// 桌面端插件：Node 内置模块（child_process / path / fs 等）由 Obsidian 运行时提供，
	// platform:"node" 让 esbuild 自动把它们标为 external，无需再依赖 builtin-modules。
	platform: "node",
	// obsidian / electron / Node 内置模块运行时由 Obsidian 桌面端提供，不打包进 main.js
	external: ["obsidian", "electron", "@codemirror/*", "@lezer/*"],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	// xterm 的 css、pty 代理的 python 以字符串打包，运行时注入 / spawn
	loader: { ".css": "text", ".py": "text" },
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
